const database = db.getSiblingDB('task_planning_mongo');

database.task_activity.deleteMany({});
database.task_comments.deleteMany({});
database.notification_log.deleteMany({});

database.task_activity.insertMany([
  {
    taskId: Long('1'),
    goalId: Long('1'),
    type: 'task_created',
    actor: { userId: Long('1'), login: 'alexey', displayName: 'Alexey Sokolov' },
    payload: { title: 'Describe task statuses', initialStatus: 'new' },
    visibleTo: [Long('1'), Long('2'), Long('3')],
    important: false,
    createdAt: new Date('2026-05-20T08:10:00Z'),
  },
  {
    taskId: Long('1'),
    goalId: Long('1'),
    type: 'status_changed',
    actor: { userId: Long('2'), login: 'maria', displayName: 'Maria Orlova' },
    payload: { oldStatus: 'new', newStatus: 'in_progress', reason: 'Started documentation' },
    visibleTo: [Long('1'), Long('2')],
    important: true,
    createdAt: new Date('2026-05-20T10:15:00Z'),
  },
  {
    taskId: Long('1'),
    goalId: Long('1'),
    type: 'status_changed',
    actor: { userId: Long('1'), login: 'alexey', displayName: 'Alexey Sokolov' },
    payload: { oldStatus: 'in_progress', newStatus: 'done' },
    visibleTo: [Long('1'), Long('2')],
    important: true,
    createdAt: new Date('2026-05-21T15:20:00Z'),
  },
  {
    taskId: Long('2'),
    goalId: Long('1'),
    type: 'task_created',
    actor: { userId: Long('1'), login: 'alexey', displayName: 'Alexey Sokolov' },
    payload: { title: 'Implement goal task endpoint', initialStatus: 'new' },
    visibleTo: [Long('1'), Long('3')],
    important: false,
    createdAt: new Date('2026-05-21T09:00:00Z'),
  },
  {
    taskId: Long('2'),
    goalId: Long('1'),
    type: 'assignee_changed',
    actor: { userId: Long('1'), login: 'alexey', displayName: 'Alexey Sokolov' },
    payload: { oldAssigneeId: Long('2'), newAssigneeId: Long('3') },
    visibleTo: [Long('1'), Long('2'), Long('3')],
    important: false,
    createdAt: new Date('2026-05-22T11:30:00Z'),
  },
  {
    taskId: Long('3'),
    goalId: Long('2'),
    type: 'comment_added',
    actor: { userId: Long('5'), login: 'sergey', displayName: 'Sergey Volkov' },
    payload: { commentPreview: 'Checklist draft is ready' },
    visibleTo: [Long('4'), Long('5')],
    important: false,
    createdAt: new Date('2026-05-22T14:05:00Z'),
  },
  {
    taskId: Long('4'),
    goalId: Long('3'),
    type: 'deadline_changed',
    actor: { userId: Long('8'), login: 'elena', displayName: 'Elena Morozova' },
    payload: { oldDueDate: '2026-06-10', newDueDate: '2026-06-12' },
    visibleTo: [Long('7'), Long('8')],
    important: true,
    createdAt: new Date('2026-05-23T08:45:00Z'),
  },
  {
    taskId: Long('5'),
    goalId: Long('4'),
    type: 'status_changed',
    actor: { userId: Long('9'), login: 'nikita', displayName: 'Nikita Lebedev' },
    payload: { oldStatus: 'in_progress', newStatus: 'done' },
    visibleTo: [Long('6'), Long('9')],
    important: false,
    createdAt: new Date('2026-05-23T12:00:00Z'),
  },
  {
    taskId: Long('6'),
    goalId: Long('5'),
    type: 'status_changed',
    actor: { userId: Long('10'), login: 'irina', displayName: 'Irina Fedorova' },
    payload: { oldStatus: 'new', newStatus: 'in_progress' },
    visibleTo: [Long('1'), Long('10')],
    important: false,
    createdAt: new Date('2026-05-24T07:25:00Z'),
  },
  {
    taskId: Long('8'),
    goalId: Long('7'),
    type: 'task_created',
    actor: { userId: Long('8'), login: 'elena', displayName: 'Elena Morozova' },
    payload: { title: 'Draft dashboard layout', initialStatus: 'new' },
    visibleTo: [Long('3'), Long('8')],
    important: false,
    createdAt: new Date('2026-05-24T09:40:00Z'),
  },
]);

database.task_comments.insertMany([
  {
    taskId: Long('1'),
    goalId: Long('1'),
    author: { userId: Long('1'), login: 'alexey', displayName: 'Alexey Sokolov' },
    text: 'Need to describe all allowed status transitions before implementation.',
    tags: ['requirements', 'status'],
    createdAt: new Date('2026-05-20T08:30:00Z'),
    updatedAt: new Date('2026-05-20T08:30:00Z'),
  },
  {
    taskId: Long('1'),
    goalId: Long('1'),
    author: { userId: Long('2'), login: 'maria', displayName: 'Maria Orlova' },
    text: 'Added examples for new, in_progress, done and cancelled.',
    tags: ['docs', 'examples'],
    createdAt: new Date('2026-05-20T11:00:00Z'),
    updatedAt: new Date('2026-05-20T11:00:00Z'),
  },
  {
    taskId: Long('2'),
    goalId: Long('1'),
    author: { userId: Long('3'), login: 'dmitry', displayName: 'Dmitry Kuznetsov' },
    text: 'Endpoint implementation is connected to PostgreSQL storage.',
    tags: ['api', 'backend'],
    createdAt: new Date('2026-05-21T12:10:00Z'),
    updatedAt: new Date('2026-05-21T12:10:00Z'),
  },
  {
    taskId: Long('3'),
    goalId: Long('2'),
    author: { userId: Long('5'), login: 'sergey', displayName: 'Sergey Volkov' },
    text: 'Checklist contains first-day and first-week tasks.',
    tags: ['onboarding'],
    createdAt: new Date('2026-05-22T14:00:00Z'),
    updatedAt: new Date('2026-05-22T14:00:00Z'),
  },
  {
    taskId: Long('4'),
    goalId: Long('3'),
    author: { userId: Long('7'), login: 'pavel', displayName: 'Pavel Ivanov' },
    text: 'Metrics source list is attached in the report workspace.',
    tags: ['report', 'metrics'],
    createdAt: new Date('2026-05-22T16:20:00Z'),
    updatedAt: new Date('2026-05-22T16:20:00Z'),
  },
  {
    taskId: Long('5'),
    goalId: Long('4'),
    author: { userId: Long('9'), login: 'nikita', displayName: 'Nikita Lebedev' },
    text: 'Inventory is complete, only archive links remain.',
    tags: ['migration', 'done'],
    createdAt: new Date('2026-05-23T12:30:00Z'),
    updatedAt: new Date('2026-05-23T12:30:00Z'),
  },
  {
    taskId: Long('6'),
    goalId: Long('5'),
    author: { userId: Long('10'), login: 'irina', displayName: 'Irina Fedorova' },
    text: 'Priority ranking uses customer impact and implementation effort.',
    tags: ['mobile', 'priority'],
    createdAt: new Date('2026-05-24T07:40:00Z'),
    updatedAt: new Date('2026-05-24T07:40:00Z'),
  },
  {
    taskId: Long('7'),
    goalId: Long('6'),
    author: { userId: Long('2'), login: 'maria', displayName: 'Maria Orlova' },
    text: 'Support ticket categories are grouped by repeated symptoms.',
    tags: ['support', 'analysis'],
    createdAt: new Date('2026-05-24T08:10:00Z'),
    updatedAt: new Date('2026-05-24T08:10:00Z'),
  },
  {
    taskId: Long('8'),
    goalId: Long('7'),
    author: { userId: Long('3'), login: 'dmitry', displayName: 'Dmitry Kuznetsov' },
    text: 'Dashboard layout draft includes filters, summary and task table.',
    tags: ['analytics', 'ui'],
    createdAt: new Date('2026-05-24T09:55:00Z'),
    updatedAt: new Date('2026-05-24T09:55:00Z'),
  },
  {
    taskId: Long('9'),
    goalId: Long('8'),
    author: { userId: Long('5'), login: 'sergey', displayName: 'Sergey Volkov' },
    text: 'Audit checklist should include dependency and secret storage checks.',
    tags: ['security', 'audit'],
    createdAt: new Date('2026-05-24T10:25:00Z'),
    updatedAt: new Date('2026-05-24T10:25:00Z'),
  },
]);

database.notification_log.insertMany([
  {
    recipient: { userId: Long('2'), login: 'maria', displayName: 'Maria Orlova' },
    channel: 'email',
    message: { subject: 'Task status changed', body: 'Task #1 moved to in_progress.' },
    taskId: Long('1'),
    goalId: Long('1'),
    status: 'sent',
    attempts: 1,
    delivered: true,
    createdAt: new Date('2026-05-20T10:16:00Z'),
    sentAt: new Date('2026-05-20T10:16:10Z'),
  },
  {
    recipient: { userId: Long('1'), login: 'alexey', displayName: 'Alexey Sokolov' },
    channel: 'web',
    message: { subject: 'Comment added', body: 'Maria commented on task #1.' },
    taskId: Long('1'),
    goalId: Long('1'),
    status: 'read',
    attempts: 1,
    delivered: true,
    createdAt: new Date('2026-05-20T11:01:00Z'),
    readAt: new Date('2026-05-20T11:05:00Z'),
  },
  {
    recipient: { userId: Long('3'), login: 'dmitry', displayName: 'Dmitry Kuznetsov' },
    channel: 'telegram',
    message: { subject: 'Assignee changed', body: 'You are assigned to task #2.' },
    taskId: Long('2'),
    goalId: Long('1'),
    status: 'sent',
    attempts: 1,
    delivered: true,
    createdAt: new Date('2026-05-22T11:31:00Z'),
    sentAt: new Date('2026-05-22T11:31:08Z'),
  },
  {
    recipient: { userId: Long('4'), login: 'olga', displayName: 'Olga Smirnova' },
    channel: 'email',
    message: { subject: 'New onboarding comment', body: 'Checklist draft is ready.' },
    taskId: Long('3'),
    goalId: Long('2'),
    status: 'queued',
    attempts: 0,
    delivered: false,
    createdAt: new Date('2026-05-22T14:06:00Z'),
  },
  {
    recipient: { userId: Long('8'), login: 'elena', displayName: 'Elena Morozova' },
    channel: 'web',
    message: { subject: 'Deadline updated', body: 'Task #4 deadline changed to 2026-06-12.' },
    taskId: Long('4'),
    goalId: Long('3'),
    status: 'read',
    attempts: 1,
    delivered: true,
    createdAt: new Date('2026-05-23T08:46:00Z'),
    readAt: new Date('2026-05-23T08:50:00Z'),
  },
  {
    recipient: { userId: Long('6'), login: 'anna', displayName: 'Anna Petrova' },
    channel: 'sms',
    message: { subject: 'Task done', body: 'Inventory documents task is done.' },
    taskId: Long('5'),
    goalId: Long('4'),
    status: 'failed',
    attempts: 3,
    delivered: false,
    createdAt: new Date('2026-05-23T12:01:00Z'),
  },
  {
    recipient: { userId: Long('10'), login: 'irina', displayName: 'Irina Fedorova' },
    channel: 'telegram',
    message: { subject: 'Task in progress', body: 'Task #6 moved to in_progress.' },
    taskId: Long('6'),
    goalId: Long('5'),
    status: 'sent',
    attempts: 1,
    delivered: true,
    createdAt: new Date('2026-05-24T07:26:00Z'),
    sentAt: new Date('2026-05-24T07:26:05Z'),
  },
  {
    recipient: { userId: Long('2'), login: 'maria', displayName: 'Maria Orlova' },
    channel: 'email',
    message: { subject: 'Support task update', body: 'Ticket analysis comment was added.' },
    taskId: Long('7'),
    goalId: Long('6'),
    status: 'queued',
    attempts: 0,
    delivered: false,
    createdAt: new Date('2026-05-24T08:11:00Z'),
  },
  {
    recipient: { userId: Long('3'), login: 'dmitry', displayName: 'Dmitry Kuznetsov' },
    channel: 'web',
    message: { subject: 'Dashboard task created', body: 'Draft dashboard layout is ready for work.' },
    taskId: Long('8'),
    goalId: Long('7'),
    status: 'read',
    attempts: 1,
    delivered: true,
    createdAt: new Date('2026-05-24T09:56:00Z'),
    readAt: new Date('2026-05-24T10:00:00Z'),
  },
  {
    recipient: { userId: Long('5'), login: 'sergey', displayName: 'Sergey Volkov' },
    channel: 'email',
    message: { subject: 'Security checklist', body: 'Audit checklist comment was added.' },
    taskId: Long('9'),
    goalId: Long('8'),
    status: 'sent',
    attempts: 1,
    delivered: true,
    createdAt: new Date('2026-05-24T10:26:00Z'),
    sentAt: new Date('2026-05-24T10:26:07Z'),
  },
]);

printjson({
  task_activity: database.task_activity.countDocuments(),
  task_comments: database.task_comments.countDocuments(),
  notification_log: database.notification_log.countDocuments(),
});
